apiVersion: apps/v1
kind: Deployment
metadata:
  name: oakell-staging-be
  namespace: oakell-staging
  labels:
    app: oakell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oakell
  template:
    metadata:
      labels:
        app: oakell
    spec:
      containers:
        - name: oakell-staging
          image: 471112673244.dkr.ecr.af-south-1.amazonaws.com/oakell-staging:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: connectionstring
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: oakell-service
  namespace: oakell-staging
spec:
  selector:
    app: oakell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: oakell-staging
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: api.staging.oakell.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: oakell-service
            port:
              number: 80

