name: Deploy to AWS EKS

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1  # Specify your AWS region

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: '471112673244.dkr.ecr.af-south-1.amazonaws.com'
        ECR_REPOSITORY: 'oakell-staging'
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Create Database Secret
      run: |
        kubectl create secret generic my-db-secret \
          --from-literal=connectionstring=${{ secrets.STAGING_CONNECTION_STRING }}

    - name: Create ECR Secret for Kubernetes
      run: |
        kubectl create secret docker-registry ecr-secret \
          --docker-server=471112673244.dkr.ecr.af-south-1.amazonaws.com \
          --docker-username=AWS \
          --docker-password=${{ secrets.ECR_PASSWORD }}
    
    - name: Set up Kubeconfig
      run: |
        aws eks --region af-south-1 update-kubeconfig --name oakell-staging
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/staging-deployment.yml
