name: Continuous Integration
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - name: Restore dependencies
      run: dotnet restore ./aspnet-core/
      
    - name: Build
      run: dotnet build ./aspnet-core/ --no-restore --configuration Release
      
    # - name: Test
    #   run: dotnet test ./aspnet-core/ --no-build --verbosity normal
